/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Classes;
import Shoe_Cart_Classes.AccountList;
import Shoe_Cart_Classes.Seller;
import Shoe_Cart_Classes.Session;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class SellerEditAccount extends javax.swing.JFrame {

      /**
     * Constructs a SellerAccountScreen
     * @param aDataBase takes an AccountDataBase object
     * @param currentSession takes a Session object
     */
    public SellerEditAccount(AccountList aDataBase, Session currentSession) {
        // initializes components in the jframe 
        initComponents();
        sneakerDataBase = aDataBase;
        this.currentSession = currentSession;
        // retrieves seller that is currently in the session
        currentUser = (Seller)sneakerDataBase.retrieve(currentSession.getUserInSession());
        // Displays the window in the center of the screen, prevents resizability
        // and calls the fillInAccountPage function
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        fillInAccountPage();
    }
 /**
     * This function retrieves the currentUsers account information
     * and stores it into the text fields that are displayed on the JFrame
     * to be seen
     */
    private void fillInAccountPage()
    {
        nameField.setText(currentUser.getFullName());
        usernameField.setText(currentUser.getUserName());
        passwordField.setText(currentUser.getPassword());
        creditcardField.setText(currentUser.getCreditCard());
        CCVfield.setText(currentUser.getCCV());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        creditcardField = new javax.swing.JTextField();
        CCVfield = new javax.swing.JTextField();
        accountTypeField = new javax.swing.JTextField();
        checkSalesButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("My Account");

        jLabel2.setText("Name");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Credit Card #");

        jLabel6.setText("CCV");

        jLabel7.setText("Account");

        checkSalesButton.setText("Check Sales");
        checkSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSalesButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(nameField)
                            .addComponent(usernameField)
                            .addComponent(passwordField)
                            .addComponent(creditcardField)
                            .addComponent(CCVfield, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(accountTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkSalesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goBackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkSalesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editButton))
                .addGap(4, 4, 4)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(goBackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditcardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CCVfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSalesButtonActionPerformed
         SalesScreen sellerStats = new SalesScreen(sneakerDataBase, currentSession);
        sellerStats.setVisible(true);
        sellerStats.setAlwaysOnTop(true);
        sellerStats.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_checkSalesButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
         // the if and else if statements are ran depending on the state of the 
        // edit-save button that is on the screen. When the screen first loads up
        // the button is currently in a false state, in which the button text shows
        // "Edit Account". If the button is clicked the state is changed from false
        // to true. This disables the return to inventory button and sale statistics
        // button that is on screen and allows the textfields to be changed.
        // When the button is in a false state the textfields are uneditable.
        // The same character length and username avaliability checks are in place
        // as the sign up screen. When the user decides to save any changes, the textfields
        // are overwritten with their new values, and the current user account information
        // is also changed (the actual object instance).
        if(!editState) {
            editState = true;
            goBackButton.setEnabled(false);
            checkSalesButton.setEnabled(false);
            editButton.setText("Save Changes");
            nameField.setEditable(true);
            passwordField.setEditable(true);
            creditcardField.setEditable(true);
            CCVfield.setEditable(true);
        }
        else if(editState) {
            String[] allUserInput = new String[5];
            allUserInput[0] = nameField.getText().trim();
            allUserInput[2] = passwordField.getText().trim();
            allUserInput[3] = creditcardField.getText().trim();
            allUserInput[4] = CCVfield.getText().trim();
        
            if(allUserInput[0].length() < 1) {
                JOptionPane.showMessageDialog(null, "Cannot leave full name field blank", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            if(allUserInput[2].length() < 6) {
                JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            if(allUserInput[3].length() < 16 || allUserInput[3].length() >= 17) {
                JOptionPane.showMessageDialog(null, "Incorrect Credit Card Length", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else {
                for(int i = 0; i < allUserInput[3].length(); i++) {
                    if(Character.isDigit(allUserInput[3].charAt(i))) {
                   
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, "credit card number cannot contains characters or symbols", "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }
        
            if(allUserInput[4].length() < 3 || allUserInput[4].length() >= 4) {
                JOptionPane.showMessageDialog(null, "CCV number has incorrect length", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            editState = false;
            currentUser.setFullName(allUserInput[0]);
            currentUser.setPassword(allUserInput[2]);
            currentUser.setCreditCard(allUserInput[3]);
            currentUser.setCCV(allUserInput[4]);
            
            currentUser.getList().changeProductOwnerShip(allUserInput[1]);
            
            editButton.setText("Edit Account");
            nameField.setEditable(false);
            passwordField.setEditable(false);
            creditcardField.setEditable(false);
            CCVfield.setEditable(false);
            goBackButton.setEnabled(true);
            checkSalesButton.setEnabled(true);
            
            currentSession.setUserInSession(currentUser.getUserName());
            
            JOptionPane.showMessageDialog(null, "Changes were successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        this.dispose();
        SellerInventoryScreen backToInventory = new SellerInventoryScreen(sneakerDataBase, currentSession);
        backToInventory.setVisible(true);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private final AccountList sneakerDataBase;
    private final Seller currentUser;
    private final Session currentSession;
    private boolean editState = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCVfield;
    private javax.swing.JTextField accountTypeField;
    private javax.swing.JButton checkSalesButton;
    private javax.swing.JTextField creditcardField;
    private javax.swing.JButton editButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
