/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Classes;
import Shoe_Cart_Classes.AccountList;
import Shoe_Cart_Classes.Customer;
import Shoe_Cart_Classes.Seller;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Constructs a SignUp object
     * @param _DataBase takes an Account DataBase object
     */
    public SignUp(AccountList _DataBase) {
        initComponents();
        SneakerDataBase = _DataBase;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        reenterPasswordLabel = new javax.swing.JLabel();
        creditcardLabel = new javax.swing.JLabel();
        CCVLabel = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        accountTypeLabel = new javax.swing.JLabel();
        AccountSelectComboBox = new javax.swing.JComboBox<>();
        fullNameInputField = new javax.swing.JTextField();
        usernameInputField = new javax.swing.JTextField();
        passwordInputField = new javax.swing.JTextField();
        reenterPasswordInputField = new javax.swing.JTextField();
        creditcardInputField = new javax.swing.JTextField();
        CCVInputField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Sign Up");

        fullNameLabel.setText("Full Name");

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        reenterPasswordLabel.setText("ReEnter Password");

        creditcardLabel.setText("Credit Card");

        CCVLabel.setText("CCV");

        createAccountButton.setText("Create");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        accountTypeLabel.setText("Account Type");

        AccountSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Seller" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CCVInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reenterPasswordInputField)
                            .addComponent(usernameLabel)
                            .addComponent(fullNameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(reenterPasswordLabel)
                            .addComponent(creditcardLabel)
                            .addComponent(CCVLabel)
                            .addComponent(fullNameInputField)
                            .addComponent(usernameInputField)
                            .addComponent(passwordInputField)
                            .addComponent(creditcardInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountTypeLabel)
                            .addComponent(AccountSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAccountButton)
                            .addComponent(cancelButton))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(fullNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(AccountSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(createAccountButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reenterPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reenterPasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(creditcardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditcardInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CCVLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CCVInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Function that is called from within an ActionListener which reacts to the
     * create account button that is on the Sign up Screen
     * @param evt takes an ActionEvent object
     */
    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        String[] allUserInput = new String[6]; 
        int accountTypeSelection = 2;
        
        if(AccountSelectComboBox.getSelectedIndex() == 0)
            accountTypeSelection = 0;
        
        else if(AccountSelectComboBox.getSelectedIndex() == 1)
            accountTypeSelection = 1;
        
        allUserInput[0] = fullNameInputField.getText().trim();
        allUserInput[1] = usernameInputField.getText().trim();
        allUserInput[2] = passwordInputField.getText().trim();
        allUserInput[3] = reenterPasswordInputField.getText().trim();
        allUserInput[4] = creditcardInputField.getText().trim();
        allUserInput[5] = CCVInputField.getText().trim();
        
        // The following if statements essentially check for empty fields in the textfields,
        // and it checks for specified lengths on username, password, creditcard and ccv fields.
        // Below is also a check to see if the username exists in the DataBase already.
        // If the username does exists it notifies the user its taken and prevents account creation
        // if not the program proceeds with creating the account. Below also, the account is created
        // depending on what the user chose the account type to be via the combo box on screen
        // once the account is successfully created and stored in the DataBase, the screen is disposed
        // off and the program returns to the login screen
        if(allUserInput[0].length() < 1) {
            JOptionPane.showMessageDialog(null, "Cannot leave full name field blank", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(allUserInput[1].length() < 5 || allUserInput[1].length() > 16) {
            JOptionPane.showMessageDialog(null, "Username must be between 5 and 16 characters", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(allUserInput[2].length() < 6) {
            JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!allUserInput[2].equals(allUserInput[3])) {
            JOptionPane.showMessageDialog(null, "Password does not match", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(allUserInput[4].length() < 16 || allUserInput[4].length() >= 17) {
            JOptionPane.showMessageDialog(null, "Incorrect Credit Card Length", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else {
            for(int i = 0; i < allUserInput[4].length(); i++) {
                if(Character.isDigit(allUserInput[4].charAt(i))) {
                   // do nothing
                } 
                else {
                    JOptionPane.showMessageDialog(null, "credit card number cannot contains characters or symbols", 
                                                  "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }
        
        if(allUserInput[5].length() < 3 || allUserInput[5].length() >= 4) {
            JOptionPane.showMessageDialog(null, "CCV number has incorrect length", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(SneakerDataBase.search(allUserInput[1])) {
            JOptionPane.showMessageDialog(null, "The username: " + allUserInput[1] + " is already taken", 
                                          "Error", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(accountTypeSelection == 0) { 
                Customer aNewCustomer = new Customer(allUserInput[0], allUserInput[1], allUserInput[2], allUserInput[4], allUserInput[5]);
                SneakerDataBase.insert(aNewCustomer);
                JOptionPane.showMessageDialog(null, "\tSignup Successful, Please log in.", "Success!", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
                SignInScreen backToLogin = new SignInScreen(SneakerDataBase);
                backToLogin.setVisible(true);
            }
            else if(accountTypeSelection == 1) {
                Seller aNewSeller = new Seller(allUserInput[0], allUserInput[1], allUserInput[2], allUserInput[4], allUserInput[5]);
                SneakerDataBase.insert(aNewSeller);
                JOptionPane.showMessageDialog(null, "\tSignup Successful, Please log in.", "Success!", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
                SignInScreen backToLogin = new SignInScreen(SneakerDataBase);
                backToLogin.setVisible(true);
            }
        }
                              
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
     // disposes of the signup screen completely
        this.dispose();
        // creates a new instance of the login screen
        SignInScreen backToLogin = new SignInScreen(SneakerDataBase);
        // set the login screen view to visible
        backToLogin.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

                                    

    
    
  private AccountList SneakerDataBase;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountSelectComboBox;
    private javax.swing.JTextField CCVInputField;
    private javax.swing.JLabel CCVLabel;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JTextField creditcardInputField;
    private javax.swing.JLabel creditcardLabel;
    private javax.swing.JTextField fullNameInputField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField passwordInputField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField reenterPasswordInputField;
    private javax.swing.JLabel reenterPasswordLabel;
    private javax.swing.JTextField usernameInputField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
